language: ruby

cache: bundler

addons:
  apt:
    packages:
      - redis-server

services:
  - redis-server

before_install:
  - sudo sed -e 's/^bind.*/bind 127.0.0.1/' /etc/redis/redis.conf > redis.conf
  - sudo mv redis.conf /etc/redis
  - sudo service redis-server start
  - echo PING | nc localhost 6379

rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7

before_script:
  - git config --local user.email "travis@travis.ci"
  - git config --local user.name "Travis CI"

script:
  - redis-cli --version
  - bundle exec rspec
  - bundle exec overcommit --sign
  - bundle exec overcommit --run
